### PR TITLE
🐛  Support POST workflow verification for inter-repo reusable workflows

### LINKED ISSUE #300: Workflow verification doesn't support re-usable workflows
The scorecard-webapp doesn't support repos which use a reusable workflow from another repository.

When Scorecard action POSTs the JSON to the webapp, the webapp tries to download and verify the workflow, but the logic currently assumes the workflow always comes from the same repo. The API used to download the workflow file then
fails with a 404 error, leading to a vague 500 error on the original POST from action to webapp:
```
error processing signature: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}
```
https://github.com/gabibguti/helm-sigstore/actions/runs/3697754335/jobs/6300965360#step:4:1207

Triaging the bug:
```
// from the sigstore/fulcio x509 cert (which also has "https://github.com" out front but we discard earlier
workflowRef := "/gabibguti/community/.github/workflows/reusable-scorecard.yml@refs/heads/main"
// from the fact that scorecard action hits "projects/github.com/gabibguti/helm-sigstore"
repoFullName := "gabibguti/helm-sigstore"

// ind is -1 here and isn't checked. which leads to the gibberish
ind := strings.Index(workflowRef, repoFullName) + len(repoFullName) + 1

workflowPath := workflowRef[ind:]
// note: another index call whose value isn't checked
workflowPath = workflowPath[:strings.Index(workflowPath, "@")]

// workflow path is now "ithub/workflows/reusable-scorecard.yml"
```

which effective tries to fetch a non-existant file: `gabibguti/helm-sigstore/contents/ithub/workflows/reusable-scorecard.yml`
```
// org = "gabibguti"
// repo = "helm-sigstore"
// info.workflowPath = "ithub/workflows/reusable-scorecard.yml"
client.Repositories.GetContents(ctx, org, repo, info.workflowPath, opts)
```

### PR DESCRIPTION
**Pull request by spencerschrock**
The Scorecard action can't be used as a reusable workflow from another repo if `publish_results` is `true`.

When Scorecard action POSTs the JSON to the webapp, the webapp tries to download and verify the workflow, but the logic currently assumes the workflow always comes from the same repo. The API used to download the workflow file then
fails with a 404 error, leading to a vague 500 error on the original POST from action to webapp:

```
error processing signature: http response 500, status: 500 Internal Server Error, error: {"code":500,"message":"something went wrong and we are looking into it."}
``` 

This PR adds logic to handle scenarios where a reusable workflow file is in a different repo than the repo being analyzed:

- In scenarios where the workflow file and the repo are the same, the behavior is unchanged (workflow file is downloaded using the cert commit SHA).
- In scenarios where the workflow file is in a different repo, the cert commit SHA can obviously no longer be used. The ref used in this case is the `workflow_ref` from the x509 cert produced by sigstore/Fulcio during Scorecard action:
https://github.com/sigstore/fulcio/blob/4114d0975133e97ac270c3ca01920fe4dfccafd4/docs/oidc.md#github

Fixes #300

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Thanks

**Review by azeemshaikh38 — APPROVED** [review]
Thanks! Could you add the associated issue for this PR?

**Comment by spencerschrock** [comment]
I don't believe there was any associated issue filed. I can create one, but it will just contain the same text as this PR.

**Comment by naveensrinivasan** [comment]
> I don't believe there was any associated issue filed. I can create one, but it will just contain the same text as this PR.

What made you fix this? Did someone complain? If so, you could create an issue with that reference. HTH

**Pull request merged**
