### PR TITLE
✨ Update production deployment

### PR DESCRIPTION
**Pull request by azeemshaikh38**
Part of #59

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Thanks!

**Review by Paradiselife84 — COMMENTED** [review]
https://github.com/actions/starter-workflows/pull/1480#issue-1174231873
Duplicate of # @azeemshaikh38

**Review by naveensrinivasan — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
@dependabot rebase

**Comment by naveensrinivasan** [comment]
@dependabot merge

**Review by naveensrinivasan — APPROVED** [review]

**Comment by azeemshaikh38** [comment]
Something off about this PR - I'm unable to merge. Will close and retry.

**Pull request closed without merging**
