### PR TITLE
:seedling: Unit tests for extract cert info

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Created unit tests for `extractCertInfo`
- Updated the error to be a standard error so that it is easier to test.
- The `extractCertInfo` - 100% code coverage. 
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  Do you know why this is failing? https://github.com/ossf/scorecard-webapp/runs/7695059399?check_suite_focus=true

**Review by azeemshaikh38 — APPROVED** [review]

**Comment by azeemshaikh38** [comment]
> @azeemshaikh38 Do you know why this is failing? https://github.com/ossf/scorecard-webapp/runs/7695059399?check_suite_focus=true

So the license checker in our CI thinks that there should be 1 less space before "http://www.apache.org" in app/post_results_test.go file. If you remove that space I think this should work.

Thanks for adding all these tests!

**Comment by naveensrinivasan** [comment]
> > @azeemshaikh38 Do you know why this is failing? https://github.com/ossf/scorecard-webapp/runs/7695059399?check_suite_focus=true
> 
> So the license checker in our CI thinks that there should be 1 less space before "http://www.apache.org" in app/post_results_test.go file. If you remove that space I think this should work.
> 
> Thanks for adding all these tests!

I did that and still it is failing https://github.com/ossf/scorecard-webapp/runs/7780408073?check_suite_focus=true _sigh_

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 Thank you! for fixing the header issue

**Pull request merged**
