### PR TITLE
add logo change salmon

### PR DESCRIPTION
**Pull request by hythloda**
This is adding a logo to the homepage and changing the base color from the salmon to white. I could not get local deployment to work and thus could not test this locally. If someone could test it before publishing that would be fantastic. Otherwise I will try to test again locally.

### CODE REVIEW

**Comment by hythloda** [comment]
Nope still not ready

**Comment by spencerschrock** [comment]
There are some local dev instructions in https://github.com/ossf/scorecard-webapp/tree/ae31464332a8aeb183980eef0db5555b3d440111/scorecards-site#build-setup

I'm able to browse an instance at `localhost:3000` using
```shell
yarn install
yarn dev
```

**Comment by hythloda** [comment]
> There are some local dev instructions in https://github.com/ossf/scorecard-webapp/tree/ae31464332a8aeb183980eef0db5555b3d440111/scorecards-site#build-setup
> 
> I'm able to browse an instance at `localhost:3000` using
> 
> ```shell
> yarn install
> yarn dev
> ```

Thanks I will give that a try!

**Comment by afmarcum** [comment]
I heard back from LF legal about whether the addition of the goose is needed for the trademark process. Scorecard's goose is considered a mascot and not a logo, therefore we do not need to change anything on the website. 

The important detail is that the full name OpenSSF Scorecard (singular) is displayed the website and it is already.

**Pull request closed without merging**
